name: Docker CI CD

on:
  push:
    branches: [docker-build-deploy]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: prod
          push: true
          # platforms: linux/arm64/v8 #  Specify the target platform for oracle arm, default is linux/amd64
          tags: ghcr.io/${{ github.repository }}/test:latest
